### ISSUE TITLE
embed mode is not working (PR #342)

### ISSUE THREAD

**Issue by ntraut** [neuroanatomy/BrainBox#385]
i did a basic html file to test the embed mode:
```html
<html>
    <header></header>
    <body>
        <iframe src="http://localhost:3001/project/testp/embed" allowfullscreen width="600" height="600" frameBorder="0" />
    </body>
</html>
```
if i open it directly i get the error:
```
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at embed (/BrainBox3/controller/project/project.controller.js:722:22)
```

if i open it through http server i get the error:
```
  const disallowedDomains = req.user.authorizedHostsForEmbedding.split('\n') || [];

TypeError: Cannot read properties of undefined (reading 'authorizedHostsForEmbedding')
    at embed (/BrainBox3/controller/project/project.controller.js:723:38)
```

in both cases brainbox crashes after the error. error should at least be handled to avoid the crash.
i tried to add those hosts to my authorized hosts list but i still get the same errors:
```
localhost
127.0.0.1
```

**Comment by ntraut** [comment]
i don't understand how the user authentication is supposed to work, and what is the use of it. currently it is trying to read authorised hosts for the logged user, but no user is logged in embed mode...
